 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: dotnet clean 
       - run: dotnet restore
       - run: dotnet build
       - run: dotnet publish --configuration Release
       - run: dotnet pack --configuration Release
       - store_artifacts:
          path: /artifacts
